server: 
  port: 8383 
spring: 
  application: 
    name: gateway-service
  config: 
    import: "optional:configserver:"   
  cloud: 
    config: 
      discovery: 
        serviceId: config-service
        enabled: true
    gateway:
       default-filters:
       - TokenRelay= 
       routes:
       - id: checkout-service
         uri: lb://checkout-service
         predicates:
          - Path=/api/checkout/**


       - id: products-service
         uri: lb://products-service
         predicates:
          - Path=/api/products/**
  
  profiles:
    active: dev

Spring:
  security:
   oauth2:
    resourceserver:
     jwt:
      issuer-uri: http://localhost:8080/realms/Tienda		
